# Generated by nixos-generate-config during installation.
# Run: sudo nixos-generate-config --no-filesystems --root /mnt
# Then replace this file with /mnt/etc/nixos/hardware-configuration.nix
{ ... }: { }
