# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- mako
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- swaybg -i ~/.config/omarchy/current/background -m fill
exec-once = uwsm-app -- swayosd-server

# Auto-launch apps on startup into specific workspaces
exec-once = uwsm-app -- brave
exec-once = uwsm-app -- ghostty
exec-once = uwsm-app -- code
exec-once = uwsm-app -- spotify-launcher

workspacerule = persistent:true, 1
workspacerule = persistent:true, 2
workspacerule = persistent:true, 3
workspacerule = persistent:true, 4

workspace = 1, name:www
workspace = 2, name:term
workspace = 3, name:dev
workspace = 4, name:dev2
workspace = 5, name:media

windowrulev2 = workspace 1, class:brave-browser
windowrulev2 = workspace 2, class:com.mitchellh.ghostty
windowrulev2 = workspace 3, class:code-url-handler
windowrulev2 = workspace 5, class:spotify
