# KeePassXC scratchpad
windowrule = workspace special:keepass silent, match:class org.keepassxc.KeePassXC
windowrule = float on, match:class org.keepassxc.KeePassXC
windowrule = size 1280 720, match:class org.keepassxc.KeePassXC
windowrule = center on, match:class org.keepassxc.KeePassXC

# Godot game window (CLI run)
windowrule = float on, match:class simulation-game
windowrule = size 1920 1080, match:class simulation-game
windowrule = center on, match:class simulation-game

# Godot game window (editor F5)
windowrule = float on, match:title .*DEBUG.*
windowrule = size 1920 1080, match:title .*DEBUG.*
windowrule = center on, match:title .*DEBUG.*

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hypr.land/Configuring/Variables/#cursor
cursor {
    warp_on_change_workspace = false
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
