workspacerule = persistent:true, 1
workspacerule = persistent:true, 2
workspacerule = persistent:true, 3
workspacerule = persistent:true, 4

workspace = 1, name:www
workspace = 2, name:term
workspace = 3, name:dev
workspace = 4, name:dev2
workspace = 5, name:media
